### ISSUE TITLE
Error on "make html"

### ISSUE THREAD

**Issue by Rohit-Gupta-IIC** [stratisproject/pyStratis#1]
On running "make html" in docs, i got the following error
```
Extension error:
Could not import extension sphinxcontrib.napoleon (exception: No module named 'sphinxcontrib.napoleon')
````

**Comment by TjadenFroyda** [comment]
You'll need to pip install that package, but this was changed to sphinx.ext.napoleon later (no need for package install).

Up to date docs can be found at pystratis.rtfd.io[pystratis.rtfd.io](http://pystratis.rtfd.io)
